import Phaser from 'phaser';

export const EventBus = new Phaser.Events.EventEmitter();

export const EVENTS = {
    BOX_PICKED: 'BOX_PICKED',
    BOX_DROPPED: 'BOX_DROPPED',
    BOX_CANCELLED: 'BOX_CANCELLED',
    BOX_MERGE_ATTEMPT: 'BOX_MERGE_ATTEMPT',
    BOX_MERGE_SUCCESS: 'BOX_MERGE_SUCCESS',
    BOX_MERGE_REJECTED: 'BOX_MERGE_REJECTED',
    
    // Grid & Spawn Events
    BOX_CREATED: 'BOX_CREATED',
    BOX_REMOVED: 'BOX_REMOVED',
    GRID_FULL: 'GRID_FULL',
    GRID_AVAILABLE: 'GRID_AVAILABLE',
    
    // Level Events
    BOX_LEVEL_UP: 'BOX_LEVEL_UP',
    BOX_MAX_LEVEL: 'BOX_MAX_LEVEL',
    
    // Economy & Shop Events
    BOX_INCOME: 'BOX_INCOME',
    SHOP_BUY_REQUEST: 'SHOP_BUY_REQUEST',
    SHOP_BUY_SUCCESS: 'SHOP_BUY_SUCCESS',
    SHOP_BUY_FAILED: 'SHOP_BUY_FAILED',
    
    // Save & State Events
    REQUEST_SAVE_DATA: 'REQUEST_SAVE_DATA',
    GAME_STATE_UPDATED: 'GAME_STATE_UPDATED',
    
    RESOURCE_ADD: 'RESOURCE_ADD',
    RESOURCE_SPEND: 'RESOURCE_SPEND',
    RESOURCE_CHANGED: 'RESOURCE_CHANGED',
    
    // Haptics
    HAPTIC_LIGHT: 'HAPTIC_LIGHT',
    HAPTIC_MEDIUM: 'HAPTIC_MEDIUM',
    HAPTIC_HEAVY: 'HAPTIC_HEAVY',
    
    // Progression & UI
    STAGE_ADVANCED: 'STAGE_ADVANCED',
    PROGRESSION_SCORE_UPDATED: 'PROGRESSION_SCORE_UPDATED',
    SHIPMENT_COMPLETED: 'SHIPMENT_COMPLETED',
    GAME_PRESTIGED: 'GAME_PRESTIGED',
    REWARD_GRANTED: 'REWARD_GRANTED',
    REWARD_PREVIEW: 'REWARD_PREVIEW',
    
    // Truck Events
    GOLDEN_TRUCK_SPAWNED: 'GOLDEN_TRUCK_SPAWNED',
    GOLDEN_TRUCK_ARRIVED: 'GOLDEN_TRUCK_ARRIVED',
    GOLDEN_TRUCK_DEPARTED: 'GOLDEN_TRUCK_DEPARTED'
} as const;
